version: '3.9'

services:
    mqtt:
        container_name: mqtt
        restart: always
        build: ./mqtt
        ports:
            - 1883:1883

    sensor_logger:
        container_name: sensor_logger
        restart: always
        build: ./sensor_logger
        volumes:
            - /sys:/sys
            - /home/pi/appdata:/db
            - /home/pi/appdata/certbot/letsencrypt:/etc/letsencrypt/
        depends_on:
            - mqtt
        ports:
            - 42660:42660
        privileged: true

    ddns:
        container_name: ddns
        restart: always
        build: ./ddns
        network_mode: host

    certbot:
        image: certbot/certbot:arm32v6-latest
        container_name: certbot
        restart: always
        ports:
            - 80:80
        volumes:
            - /home/pi/appdata/certbot/letsencrypt:/etc/letsencrypt
            - /home/pi/appdata/certbot/www:/var/www/certbot
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew -n; sleep 24h & wait $${!}; done;'"