version: '3.9'

services:
  mqtt:
    container_name: mqtt
    restart: always
    build: ./mqtt
    ports:
      - 1883:1883

  sensor_logger:
    container_name: sensor_logger
    restart: always
    build: ./sensor_logger
    volumes:
      - /sys:/sys
      - /home/pi/appdata:/db
    depends_on:
      - mqtt
    ports:
      - 0.0.0.0:42660:42660
    privileged: true

  duckdns:
    container_name: duckdns
    build: ./duckdns
    #environment:
        #- PUID=1000 #optional
        #- PGID=1000 #optional
        #- TZ=Europe/Stockholm
        #- SUBDOMAINS=subdomain1
        #- TOKEN=token
        #- LOG_FILE=false #optional
    #volumes:
    #    - /path/to/appdata/config:/config #optional
    restart: always