version: '3.9'

services:
  mqtt:
    container_name: mqtt
    restart: always
    build: ./mqtt
    ports:
      - 1883:1883

  sensor_logger:
    container_name: sensor_logger
    restart: always
    build: ./sensor_logger
    volumes:
      - /sys:/sys
      - /home/pi/appdata:/db
      - /etc/letsencrypt/:/certs/
    depends_on:
      - mqtt
    ports:
      - 0.0.0.0:42660:42660
    privileged: true

  certbot:
    build: ./certbot
    restart: always
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    ports:
      - 80:80