version: '3.9'

services:
  mqtt:
    container_name: mqtt
    restart: always
    build: ./mqtt
    ports:
      - 1883:1883

  memcached:
    container_name: memcached
    image: memcached:alpine
    restart: always
    ports:
      - 11211:11211
    command: ["memcached"]


  sensor_logger:
    container_name: sensor_logger
    volumes:
      - /home/pi/appdata:/db
      #- /var/run/memcached:/memcached
    restart: always
    build: ./sensor_logger
    environment:
      - TZ=Europe/Stockholm
    depends_on:
      - memcached
      - mqtt

  flask:
    container_name: flask
    restart: always
    build: ./flask
    expose:
      - 8000
    command: gunicorn app.__init__:create_app() -w 4 -b 0.0.0.0:8000 #--max-requests 10
    environment:
      - TZ=Europe/Stockholm
    volumes:
      - /home/pi/appdata:/db
      #- /var/run/memcached:/memcached:or
    depends_on:
      - sensor_logger

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - flask

    certbot:
      image: certbot/certbot