version: '3.8'

services:
  flask:
    container_name: flask
    restart: always
    build: ./flask
    expose:
      - 8000
    command: gunicorn app.__init__:create_app() -w 1 -b 0.0.0.0:8000
    volumes:
      - /var/www:/db
      - /var/run/memcached:/memcached/


  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - flask